######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 28 13:22:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../src

# Input
HEADERS += AppWidget.hpp
SOURCES += AppWidget.cpp example.cpp
    
LIBS += -L../ -lqteffects
